import { useState } from "react";
import { CalendarDays, Camera, CheckCircle2, Mail, ShieldCheck, User } from "lucide-react";
import { useAuthStore } from "../store/useAuthStore";

export const ProfilePage = () => {
  const { authUser, isUpdatingProfile, updateProfile } = useAuthStore();
  const [selectedImg, setSelectedImg] = useState(null);
  const handleImageUpload = (event) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async () => { setSelectedImg(reader.result); await updateProfile({ profilePic: reader.result }); };
    reader.readAsDataURL(file);
  };
  const joined = authUser?.createdAt ? new Date(authUser.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) : "Not available";

  return <main className="min-h-screen bg-[#f5f8f7] px-3 pb-16 pt-[84px] sm:px-6 sm:pt-[104px]"><div className="mx-auto max-w-5xl"><section className="relative overflow-hidden rounded-[30px] bg-[#062e28] px-6 py-10 text-white sm:px-10 sm:py-12"><div className="absolute -right-20 -top-32 size-80 rounded-full border border-white/10"/><span className="relative text-xs font-semibold uppercase tracking-[.18em] text-[#65d6b4]">Customer account</span><h1 className="relative mt-3 text-5xl font-semibold tracking-[-.055em] sm:text-6xl">Your profile</h1><p className="relative mt-4 max-w-xl text-white/60">Manage your identity and review your PharmaCart account information.</p></section>
  <section className="mt-6 grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="rounded-[28px] border border-[#e2ebe7] bg-white p-6 text-center shadow-[0_18px_50px_rgba(7,63,53,.07)]"><div className="relative mx-auto w-fit"><div className="rounded-full bg-[#dff8ef] p-2"><img src={selectedImg || authUser?.profilePic || "/avatar.png"} alt={`${authUser?.fullName || "User"} profile`} className="size-36 rounded-full bg-white object-cover"/></div><label htmlFor="avatar-upload" className={`absolute bottom-1 right-1 grid size-12 cursor-pointer place-items-center rounded-full border-4 border-white bg-[#159a74] text-white shadow-lg transition hover:scale-105 ${isUpdatingProfile ? "pointer-events-none animate-pulse" : ""}`} aria-label="Upload profile photo"><Camera className="size-5"/><input id="avatar-upload" type="file" className="sr-only" accept="image/*" onChange={handleImageUpload} disabled={isUpdatingProfile}/></label></div><h2 className="mt-5 text-2xl font-semibold tracking-[-.04em] text-[#10211b]">{authUser?.fullName}</h2><p className="mt-1 break-all text-sm text-[#66756f]">{authUser?.email}</p><span className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#dff8ef] px-4 py-2 text-xs font-semibold text-[#087558]"><CheckCircle2 className="size-4"/>Active account</span><p className="mt-5 text-xs leading-5 text-[#8a9993]">{isUpdatingProfile ? "Uploading your new photo…" : "Use the camera button to change your profile photo."}</p></aside>
  <div className="space-y-6"><section className="rounded-[28px] border border-[#e2ebe7] bg-white p-5 shadow-[0_18px_50px_rgba(7,63,53,.07)] sm:p-7"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[#effbf7] text-[#159a74]"><User className="size-5"/></span><div><span className="text-[10px] font-semibold uppercase tracking-[.15em] text-[#159a74]">Personal details</span><h2 className="text-2xl font-semibold">Profile information</h2></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#f5f8f7] p-4"><span className="flex items-center gap-2 text-xs text-[#66756f]"><User className="size-4 text-[#159a74]"/>Full name</span><strong className="mt-2 block">{authUser?.fullName}</strong></div><div className="rounded-2xl bg-[#f5f8f7] p-4"><span className="flex items-center gap-2 text-xs text-[#66756f]"><Mail className="size-4 text-[#159a74]"/>Email address</span><strong className="mt-2 block break-all">{authUser?.email}</strong></div></div></section>
  <section className="rounded-[28px] border border-[#e2ebe7] bg-white p-5 shadow-[0_18px_50px_rgba(7,63,53,.07)] sm:p-7"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[#effbf7] text-[#159a74]"><ShieldCheck className="size-5"/></span><h2 className="text-2xl font-semibold">Account information</h2></div><div className="mt-6 divide-y divide-[#e2ebe7] rounded-2xl border border-[#e2ebe7] px-4"><div className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><span className="flex items-center gap-2 text-sm text-[#66756f]"><CalendarDays className="size-4 text-[#159a74]"/>Member since</span><strong>{joined}</strong></div><div className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><span className="flex items-center gap-2 text-sm text-[#66756f]"><ShieldCheck className="size-4 text-[#159a74]"/>Account role</span><strong className="capitalize">{authUser?.role || "customer"}</strong></div></div></section></div></section></div></main>;
};

export default ProfilePage;
